export {
  Workspace,
  DEFAULT_CHANNELS,
  type WorkspaceInfo,
  type WorkspaceUser,
  type OpenOptions,
  type BootstrapOptions,
  type ServiceContext,
} from './workspace.ts';
export { openDatabase, migrate, transact, row, rows, SCHEMA_VERSION, type SQLInputValue } from './db.ts';
export { paths, slickHome, type SlickPaths } from './paths.ts';
export {
  SlickError,
  NotFoundError,
  ValidationError,
  ConflictError,
  toSlickError,
  type SlickErrorOptions,
  type SlickErrorJson,
} from './errors.ts';
export { isRecord, errorCode, errorMessage } from './guards.ts';
export { newId, newHistoryKey, looksLikeHistoryKey, hasPrefix, ulid, ID_PREFIX } from './ids.ts';
export {
  EVENT_TYPES,
  CONVERSATION_EVENTS,
  listEvents,
  countEvents,
  maxSeq,
  recordEvent,
  hydrateEvent,
  type EventType,
  type ListEventsOptions,
  type RecordEventInput,
} from './events.ts';
export {
  SERVE_ADAPTER_KEY,
  SERVE_EFFORT_KEY,
  SERVE_MODEL_KEY,
  SERVE_MODELS_KEY,
  SERVE_MODELS_AT_KEY,
  readServeAdapter,
  readServeEffort,
  readServeModel,
  readServeModelChoices,
  normalizeModelChoices,
  type AgentService,
  type SessionListOptions,
  type StartSessionInput,
  type SessionReadOptions,
  type PullOptions,
  type PullResult,
  type ResumeOptions,
  type ResumeResult,
  type SessionPatch,
  type AgentPostInput,
  type TypingInput,
  type TypingEntry,
  type ThinkingInput,
  type ThinkingEntry,
  type ExternalTypingInput,
  type ExternalThinkingInput,
} from './agents.ts';
export { serveLockPath, readServeLock, wasEverServed, serveStatus } from './serve.ts';
export {
  BUILT_IN_ADAPTERS,
  DEFAULT_ADAPTER,
  adapterDir,
  adapterFile,
  buildAgentArgs,
  buildCommandListCall,
  buildCommandRunCall,
  buildModelListArgs,
  listAdapters,
  loadAdapter,
  lookupReported,
  normalizeAdapter,
  parseAgentReply,
  slotFires,
  supportsCommands,
  supportsModelList,
  supportsResume,
  type Adapter,
  type AdapterListing,
  type AgentCallValues,
  type AgentReply,
  type ArgGroup,
  type ArgSlot,
  type CommandCall,
  type ReplyField,
  type StreamFrame,
  type StreamSpec,
} from './adapters.ts';
export { THINK_KEY, normalizeThinking, mergeThinking } from './thinking.ts';
export {
  slugify,
  assertSlug,
  type CategoryRef,
  type ChannelInput,
  type ChannelPatch,
  type ChannelListOptions,
  type ChannelService,
} from './channels.ts';
export { type CategoryInput, type CategoryPatch, type CategoryService } from './categories.ts';
export {
  extractMentions,
  serializeMessage,
  serializeMessageRow,
  splitMessageText,
  MAX_TEXT_LENGTH,
  type MessageRow,
  type MessageService,
  type PostMessageInput,
  type MessageListOptions,
  type MessagePage,
  type MessagePatch,
  type RemoveMessageOptions,
  type Thread,
} from './messages.ts';
export { type SearchOptions, type SearchResult, type SearchService } from './search.ts';
export type {
  AgentSession,
  Author,
  AuthorKind,
  Category,
  Channel,
  ChannelCategoryRef,
  EventRecord,
  HydratedEvent,
  JsonObject,
  Message,
  MessageAuthor,
  MessageMetadata,
  ModelChoice,
  ServeStatus,
  SessionState,
  StepStatus,
  ThinkingPhase,
  ThinkingSource,
  ThinkingStep,
  ThinkingTrace,
} from './types.ts';
